#/bin/sh

# packages-source.sh

# Install source code from packages

# This program is part of the Impermanix project

# Copyright (C)  2018 Scott C. MacCallum
# scm@linux.com

# This program is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.

apt-get source apt-listchanges
apt-get source base-files
apt-get source bash
apt-get source bash-completion
apt-get source bc
apt-get source bsd-mailx
apt-get source bsdmainutils
apt-get source bsdutils
apt-get source bzip2
apt-get source ca-certificates
apt-get source console-setup
apt-get source console-setup-freebsd
apt-get source coreutils
apt-get source cpio
apt-get source dash
apt-get source dbus
apt-get source dbus
apt-get source dc
apt-get source debconf
apt-get source debconf-i18n
apt-get source debian-archive-keyring
apt-get source debian-faq
apt-get source debianutils
apt-get source devd
apt-get source dictionaries-common
apt-get source diffutils
apt-get source dmidecode
apt-get source doc-debian
apt-get source e2fslibs
apt-get source e2fsprogs
apt-get source emacs23
apt-get source emacs23-bin-common
apt-get source emacs23-common
apt-get source emacs
apt-get source emacsen-common
apt-get source emacsen-common
apt-get source file
apt-get source findutils
apt-get source fontconfig
apt-get source fontconfig-config
apt-get source ftp
apt-get source gconf2-common
apt-get source gconf-service
apt-get source geoip-database
apt-get source geom
apt-get source gettext-base
apt-get source git
apt-get source git
apt-get source git-man
apt-get source git-man
apt-get source gnupg
apt-get source gpgv
apt-get source grep
apt-get source groff-base
apt-get source grub2-common
apt-get source grub-common
apt-get source grub-pc
apt-get source grub-pc-bin
apt-get source gzip
apt-get source hicolor-icon-theme
apt-get source hicolor-icon-theme
apt-get source host
apt-get source hostname
apt-get source ifupdown
apt-get source inetutils-ping
apt-get source info
apt-get source installation-report
apt-get source install-info
apt-get source iso-codes
apt-get source kbdcontrol
apt-get source keyboard-configuration
apt-get source kfreebsd-kernel-headers
apt-get source kldutils
apt-get source krb5-locales
apt-get source less
apt-get source libacl1
apt-get source libapt-inst1.5
apt-get source libasprintf0c2
apt-get source libatk1.0-0
apt-get source libatk1.0-data
apt-get source libattr1
apt-get source libavahi-client3
apt-get source libavahi-client3
apt-get source libavahi-common3
apt-get source libavahi-common3
apt-get source libavahi-common-data
apt-get source libavahi-common-data
apt-get source libblkid1
apt-get source libbsd0
apt-get source libbz2-1.0
apt-get source libc0.1
apt-get source libcairo2
apt-get source libcam6
apt-get source libc-bin
apt-get source libclass-isa-perl
apt-get source libcomerr2
apt-get source libcroco3
apt-get source libcroco3
apt-get source libcups2
apt-get source libcurl3-gnutls
apt-get source libdatrie1
apt-get source libdatrie1
apt-get source libdbus-1-3
apt-get source libdbus-1-3
apt-get source libdbus-glib-1-2
apt-get source libdbus-glib-1-2
apt-get source libedit2
apt-get source liberror-perl
apt-get source liberror-perl
apt-get source libexpat1
apt-get source libffi5
apt-get source libfontconfig1
apt-get source libfreetype6
apt-get source libfribidi0
apt-get source libfribidi0
apt-get source libfuse2
apt-get source libgc1c2
apt-get source libgconf-2-4
apt-get source libgd2-noxpm
apt-get source libgdbm3
apt-get source libgdk-pixbuf2.0-0
apt-get source libgdk-pixbuf2.0-common
apt-get source libgeoip1
apt-get source libgeom1
apt-get source libgif4
apt-get source libgif4
apt-get source libglib2.0-0
apt-get source libglib2.0-data
apt-get source libglib2.0-data
apt-get source libgpg-error0
apt-get source libgssapi-krb5-2
apt-get source libgtk2.0-0
apt-get source libgtk2.0-bin
apt-get source libgtk2.0-common
apt-get source libgtk2.0-common
apt-get source libice6
apt-get source libice6
apt-get source libidn11
apt-get source libipx2
apt-get source libjail1
apt-get source libjasper1
apt-get source libjbig0
apt-get source libjbig0
apt-get source libjpeg8
apt-get source libk5crypto3
apt-get source libkiconv4
apt-get source libkrb5-3
apt-get source libkrb5support0
apt-get source libldap-2.4-2
apt-get source liblockfile1
apt-get source liblockfile-bin
apt-get source liblzma5
apt-get source libm17n-0
apt-get source libmagic1
apt-get source libncurses5
apt-get source libncursesw5
apt-get source libnetgraph4
apt-get source libnewt0.52
apt-get source libotf0
apt-get source libotf0
apt-get source libpam0g
apt-get source libpam-runtime
apt-get source libpango1.0-0
apt-get source libpci3
apt-get source libpcre3
apt-get source libpipeline1
apt-get source libpixman-1-0
apt-get source libpixman-1-0
apt-get source libpng12-0
apt-get source libpng12-0
apt-get source libpopt0
apt-get source libpth20
apt-get source libreadline6
apt-get source librsvg2-2
apt-get source librsvg2-common
apt-get source librtmp0
apt-get source libsasl2-modules
apt-get source libsbuf6
apt-get source libsigc++-2.0-0c2a
apt-get source libslang2
apt-get source libsm6
apt-get source libsm6
apt-get source libsqlite3-0
apt-get source libss2
apt-get source libssh2-1
apt-get source libssl1.0.0
apt-get source libswitch-perl
apt-get source libthai0
apt-get source libthai0
apt-get source libthai-data
apt-get source libthai-data
apt-get source libtiff4
apt-get source libtinfo5
apt-get source libtirpc1
apt-get source libtokyocabinet9
apt-get source libusb-0.1-4
apt-get source libuuid1
apt-get source libwrap0
apt-get source libx11-6
apt-get source libx11-data
apt-get source libxau6
apt-get source libxcb1
apt-get source libxcb-render0
apt-get source libxcb-render0
apt-get source libxcb-shm0
apt-get source libxcb-shm0
apt-get source libxcomposite1
apt-get source libxcomposite1
apt-get source libxcursor1
apt-get source libxcursor1
apt-get source libxdamage1
apt-get source libxdamage1
apt-get source libxdmcp6
apt-get source libxext6
apt-get source libxfixes3
apt-get source libxfixes3
apt-get source libxft2
apt-get source libxi6
apt-get source libxi6
apt-get source libxinerama1
apt-get source libxinerama1
apt-get source libxml2
apt-get source libxmuu1
apt-get source libxpm4
apt-get source libxpm4
apt-get source libxrandr2
apt-get source libxrandr2
apt-get source libxrender1
apt-get source libxrender1
apt-get source libxt6
apt-get source libxt6
apt-get source locales
apt-get source lock
apt-get source logrotate
apt-get source lsb-base
apt-get source lsb-release
apt-get source m17n-contrib
apt-get source m17n-contrib
apt-get source m17n-db
apt-get source m17n-db
apt-get source man-db
apt-get source manpages
apt-get source mime-support
apt-get source mlocate
apt-get source multiarch-support
apt-get source nano
apt-get source ncurses-base
apt-get source ncurses-bin
apt-get source ncurses-term
apt-get source netbase
apt-get source netcat-traditional
apt-get source openssl
apt-get source os-prober
apt-get source partial/
apt-get source passwd
apt-get source patch
apt-get source pciutils
apt-get source powerd
apt-get source procmail
apt-get source psmisc
apt-get source python-apt-common
apt-get source python-debianbts
apt-get source readline-common
apt-get source rpcbind
apt-get source rsync
apt-get source rsync
apt-get source sed
apt-get source sensible-utils
apt-get source shared-mime-info
apt-get source ssh
apt-get source sudo
apt-get source sudo
apt-get source tar
apt-get source task-english
apt-get source tasksel
apt-get source tasksel-data
apt-get source task-ssh-server
apt-get source tcpd
apt-get source time
apt-get source ttf-dejavu-core
apt-get source ucf
apt-get source vidcontrol
apt-get source vim-common
apt-get source vim-tiny
apt-get source w3m
apt-get source whiptail
apt-get source whois
apt-get source x11-common
apt-get source x11-common
apt-get source xauth
apt-get source xkb-data
apt-get source xz-utils
apt-get source zlib1g

exit 0